# Site settings
title: Chris Connelly - Web Developer
tagline: "Small Business | Big Dreams"
company: "chrisConnellyDotDev"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
logo: "https://raw.githubusercontent.com/teamallnighter/codys-house/main/assets/images/ccdd.svg"

# SEO


# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: https://github.com/teamallnighter
googleplus: gusername
instagram: igusername

# Contact
phone: "506-364-9437" # This is my real number. You should text me.
email: "me@chrisconnelly.dev" # This is my real email address. Please don't email me.

# Animations
creattie: "adfc0335539d5f5148f7" # Creattie id

# Use this for production
#sass:
#    style: compressed


exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]